modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="ymlmobs"
version="${file.jarVersion}" #mandatory
displayName="YML Mobs" #mandatory
logoFile="ymlmobs.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.ymlmobs]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ymlmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ymlmobs]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.15,)"
    ordering="AFTER"
    side="BOTH"